// Generated by EmDash on dev server start
// Do not edit manually — kept in sync for CMS page/post fields used by the theme

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Page {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	excerpt?: string;
	content?: PortableTextBlock[];
	featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	byline?: unknown;
	bylines?: ContentBylineCredit[];
}

export interface Post {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	excerpt?: string;
	content?: PortableTextBlock[];
	featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	byline?: unknown;
	bylines?: ContentBylineCredit[];
}

export interface Project {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number };
	client?: string;
	year?: string;
	summary?: string;
	content?: PortableTextBlock[];
	gallery?: unknown;
	url?: string;
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
}

declare module "emdash" {
	interface EmDashCollections {
		pages: Page;
		posts: Post;
		projects: Project;
	}
}
